### ISSUE TITLE
Class 'Watson\Breadcrumbs\BreadcrumbServiceProvider' not found

### ISSUE THREAD

**Issue by jeffreyvanhees** [dwightwatson/breadcrumbs#1]
Hi Dwight,

I got the error message `Class 'Watson\Breadcrumbs\BreadcrumbServiceProvider' not found` after registering it in `app.php`. The file does not appear to exist. What to do?

**Comment by dwightwatson** [comment]
Whoops, looks like that's a mistake in the installation instructions. I've fixed that up now. The class you're after is `Watson\Breadcrumbs\ServiceProvider::class`.
