### ISSUE TITLE
Exception after adding a 4th level of breadcrumbs

### ISSUE THREAD

**Issue by Onind** [dwightwatson/breadcrumbs#3]
i got the following error when im adding the fourth breadcrumb level
`Type error: Too few arguments to function Watson\Breadcrumbs\ServiceProvider::{closure}(), 1 passed and exactly 2 expected`

My Routes for this section:
![screen shot 2017-05-05 at 13 34 47](https://cloud.githubusercontent.com/assets/6358473/25743977/a031c8d6-3197-11e7-91e4-36ae9b699762.png)

My breadcrumbs.php
![screen shot 2017-05-05 at 13 32 46](https://cloud.githubusercontent.com/assets/6358473/25743983/a9fa7002-3197-11e7-820e-f4260b35c2ec.png)

**Comment by dwightwatson** [comment]
Thanks for getting the additional information to me.

Can I ask which route fails? Or do all routes break?

**Comment by Onind** [comment]
it only breaks on the admin.company.view.stores route.

**Comment by catalinbuletin** [comment]
I get the same error when I try to call a parent breadcrumb that needs a parameter.

to follow @Onind example, i thought I had to to something like this:

```
Breadcrumbs::for('admin.company.view.stores', function ($trail, Company $company) {
    $trail->parent('admin.company.view', [$company->id]);
    $trail->add('Stores', route('admin.company.view.stores', $company->id));
});
```
So i thought that i need to pass to the parent whatever it needs to create the trail. But I get the same error as above..

Any thoughts on this would be appreciated!

**Comment by dwightwatson** [comment]
I ran into this today as well, I'm very sorry about this. I'm on vacation at the moment and only have limited access to a computer but will try and sort this out as soon as I can. Open to any PRs that can help otherwise I hope to get to it shortly.

**Comment by catalinbuletin** [comment]
Ok, don't worry! I'll try to fix it and create a PR for it if I have any luck! Have fun!

**Comment by dwightwatson** [comment]
I think I may have identified the issue with the `parent` method and have pushed a fix in `1.0.4`. Please upgrade and let me know if you're still running into this issue.

Edit: for your example, you may need to update your call to `parent()` to lose the array. Instead, something like...

```php
$trail->parent('admin.company.view', $company->id);
```

**Comment by catalinbuletin** [comment]
Hey! It works. You have to pass in the Company model, not the ID.

`$trail->parent('admin.company.view', $company);`

Thanks!

**Comment by dwightwatson** [comment]
Cool, thanks. I've updated the docs to show how to use `parent()` when passing route parameters in now as well. As I suspect this may relate to OP's original issue and have fixed it I'll close the issue, but please let me know if it persists and I'll continue to investigate.

**Comment by Onind** [comment]
Hi,

yes it worked thank you for the fix.
