### ISSUE TITLE
Get all routes Collection

### ISSUE THREAD

**Issue by lucassmacedo** [dwightwatson/breadcrumbs#7]
Hello! How i get a collection of routes? 
I want the collection of file breadcrumbs.php ..

**Comment by dwightwatson** [comment]
It’s not something that’s exposed at the moment but would be happy to accept a PR that changed that. Curious what the use-case would be.

**Comment by lucassmacedo** [comment]
I want to create a navigation history and the breadcrumbs file already contains the named routes.

**Comment by dwightwatson** [comment]
I'm starting work on a new version. If this is still a feature you'd require please let me know.
